stages:
  - containerization
  - test
  - deployment 

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

containerization:
  stage: containerization
  tags: 
    - dind
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test:
  stage: test
  tags: 
    - dind
  script:
    - echo "This job tests something"

deployment:
  stage: deployment
  tags: 
    - dind
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20