stages:
  - containerization
  - deployment 

# image: moreillon/ci-dind:4bca50d7
# services:
#   - name: docker:19.03.12-dind
variables:
  CONTAINER_IMAGE_NAME: todoapp
containerization:
  stage: containerization
  tags: 
    - watanabe-shell
  before_script:

    - echo ${CONTAINER_REGISTRY_URL}
    - >
      aws ecr create-repository --repository-name ${CONTAINER_IMAGE_NAME}
      || echo "Repository might have already existed"
    
    # Log in to the registry (AWS credentials are stored as GitLab env variables)
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${CONTAINER_REGISTRY_URL}


  script:
    - docker build --no-cache -t ${CONTAINER_IMAGE_NAME} . 
    # - docker build --no-cache -t ${CONTAINER_IMAGE_DETECTRON2} --build-arg registry=$REGISTRY_BASE . 
    
    # # Push the container image to the container registry
    - docker push ${CONTAINER_IMAGE_NAME}
    - docker rmi ${CONTAINER_IMAGE_NAME}



deployment:
  stage: deployment
  tags:
    - watanabe-shell
  script:
    - kubectl apply -k ./

  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
