stages:
  - containerization
  - build
  - test
  - deployment 

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

docker-build-master:
  image: docker:latest
  stage: build
  tags: 
    - dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --no-cache -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
    - docker rmi ${IMAGE_NAME} 

test:
  stage: test
  tags: 
    - dind
  script:
    - docker run -dp 3000:3000 $(IMAGE_NAME)

deployment:
  stage: deployment
  tags: 
    - dind
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20