apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${APPLICATION_NAME}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - image: ${CONTAINER_IMAGE_TAGGED}
        name: ${APPLICATION_NAME}
        # env:
        # - name: MYSQL_HOST 
        #   value: ${APPLICATION_NAME}-mysql
        # - name: MYSQL_USER
        #   value: root
        # - name: MYSQL_DB
        #   value: todos
        # - name: MYSQL_PASSWORD
        #   value: secret
        ports:
        - containerPort: 3000
          name: ${APPLICATION_NAME}
      imagePullSecrets:
      - name: ${K8S_ECR_SECRET_NAME}


